packages:
  - '.'

minimumReleaseAgeExclude:
  - '@expo/image-utils@0.8.16'
  - '@expo/require-utils@55.0.7'
  - expo-location@55.1.13

patchedDependencies:
  '@vlcn.io/ws-client@0.2.0': patches/@vlcn.io__ws-client@0.2.0.patch
